use flyio::{error::Error, run};

fn main() -> Result<(), Error> {
    run()
}
